# Generated by Django 4.0.3 on 2022-03-31 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fido.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', fido.models.ShortTextField(max_length=200)),
                ('is_live', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', fido.models.ShortTextField(max_length=200)),
                ('question_type', fido.models.ShortTextField(choices=[('checkbox', 'checkbox'), ('multiple', 'multiple'), ('freeform', 'freeform'), ('signature', 'signature')])),
                ('position', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', fido.models.ShortTextField(max_length=200)),
                ('role_type', fido.models.ShortTextField(choices=[('claimable', 'claimable'), ('known_users', 'known_users')])),
                ('role_choices', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('section_name', fido.models.ShortTextField(max_length=200)),
                ('assignee_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.templaterole')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.templatequestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntakeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('template_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.templatesection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntakeRoleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_name', fido.models.ShortTextField(max_length=200)),
                ('invite_email', models.EmailField(max_length=512)),
                ('claimed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.intake')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.templaterole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntakeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflows.templatechoice')),
                ('template_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.templatequestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='intake',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.template'),
        ),
    ]
